modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="oreutils" #mandatory
version="${file.jarVersion}" #mandatory
displayName="OREutils Forge" #mandatory
logoFile="icon.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Eithan" #optional
description='''
a QoL mod for the minecraft redstone server ORE
'''

[[dependencies.oreutils]]
    modId="oreutils" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.oreutils]]
    modId="oreutils"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
